name: Build and release cloudflared

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout cloudflared source code
        uses: actions/checkout@v2
        with:
          repository: cloudflare/cloudflared
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git golang-go
      - name: Build cloudflared
        run: |
          cd cloudflared/cmd/cloudflared
          go build -o c.js
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          body: |
            This is the first release of cloudflared.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cloudflared/cmd/cloudflared/c.js
          asset_name: c.js
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
